---
title: "bt_model"
author: "Josh Marvald"
date: "6/8/2020"
output: html_document
---

```{r}
library(tidyverse)
library(BradleyTerry2)
source("merging_matches.R")

gs_matches_final2 <- gs_matches_final
```


```{r}
# only keep players with enough matches
matches_keep <-
  gs_matches_final2 %>%
  group_by(player) %>%
  summarise(matches = n()) %>%
  filter(matches >= 80) 

# leave out 2015 to check
gs_decade_small <- 
  gs_decade %>%
  filter(winner_name %in% matches_keep$player & loser_name %in% matches_keep$player) %>%
  separate(tourney_id, into = c("year", "tourn_id"), sep = "-" ) %>%
  filter(year != 2015) 

gs_decade_small_2015 <-
  gs_decade %>%
  filter(winner_name %in% matches_keep$player & loser_name %in% matches_keep$player) %>%
  separate(tourney_id, into = c("year", "tourn_id"), sep = "-" ) %>%
  filter(year == 2015)
```

```{r}
# split data into winners and losers
winners_df <-
  gs_decade_small %>%
  select(winner_name, w_serveperc, w_secondserve) %>%
  mutate(win1 = 1, id = as.factor(winner_name), first_serve = w_serveperc)

winners_2015 <-
  gs_decade_small_2015 %>%
  select(winner_name, w_serveperc, w_secondserve) %>%
  mutate(win1 = 1, id = as.factor(winner_name), first_serve = w_serveperc)

losers_df <-
  gs_decade_small %>%
  select(loser_name, l_serveperc, l_secondserve) %>%
  mutate(win2 = 0, id = as.factor(loser_name), first_serve = l_serveperc) 

losers_2015 <-
  gs_decade_small_2015 %>%
  select(loser_name, l_serveperc, l_secondserve) %>%
  mutate(win2 = 0, id = as.factor(loser_name), first_serve = l_serveperc)
```


```{r}
levels(winners_df$id)
levels(losers_df$id)

levels(winners_2015$id)
levels(losers_2015$id)
```


```{r}
# fit models

# mod with just player 
mod1 <- BTm(cbind(win1, win2), player1 = winners_df, player2 = losers_df, formula = ~ id + first_serve:id + first_serve, id = "id", data = gs_decade_small)

summary(mod1)

# mod with player and tournament
mod2 <- BTm(cbind(win1, win2), player1 = winners_df, player2 = losers_df, formula = ~ id + first_serve:id + first_serve + tourney_name, id = "id", data = gs_decade_small)

summary(mod2)
```


```{r}
test <- mod1$coefficients  ## extract model coefficients
test2 <- names(mod1$coefficients) %>%
  str_replace("id", "") ## extract names of model coefficients
ref <- levels(mod1$player1$id)[1] ## see who is the reference group

nonref <- data.frame(name = test2, coefficient = test) ## coefficients
## for the non-reference group

serve_coef <- mod1$coefficients[names(mod1$coefficients) == "first_serve"]
## extract base serve coefficient

## create a data frame for the reference group
reference_group <- data.frame(name = c(ref, str_c(ref, ":first_serve")),
  coefficient = c(0, 0))

test_df <- bind_rows(reference_group, nonref) %>% ## bind reference and non-reference coefficients
  separate(name, into = c("player", "term"), sep = ":") %>% ## separate names from the interaction with serve percentage
  mutate(term = case_when(is.na(term) == TRUE ~ "intercept",
    TRUE ~ "first_serve")) %>% ## label terms intercept for intercepts and first_serve for slopes
  mutate(new_coefficient = case_when(term == "intercept" ~ coefficient,
    term == "first_serve" ~ coefficient + serve_coef)) %>% ## define the slope by adding the serve coefficient to the value of first_serve for a particular player (similar to what you would do in STAT 213 when you had an interaction between a categorical and quantitative variable and you wanted to make predictions)
  filter(player != "first_serve") %>% ## get rid of the slope that we just added: it's useless now
  select(player, term, new_coefficient) %>% ## only keep relevant variables
  pivot_wider(names_from = c(term), values_from = new_coefficient) ## tidy up by having each player occupy his own row

## create fake data to make predictions on
## will need to put the data set from 2015 into this format
newdata1 <- data.frame(player = c("Rafael Nadal", "Rafael Nadal"), first_serve_perc = c(0.7, 0.5)) 
newdata2 <- data.frame(player = c("Fernando Verdasco", "Roger Federer"), first_serve_perc = c(0.6, 0.8))


# add player column to join with test_df
winners_2015 <-
  winners_2015 %>%
  mutate(player = winner_name) 

losers_2015 <-
  losers_2015 %>%
  mutate(player = loser_name)

## obtain predicted "abilities"
ab1 <- winners_2015 %>% left_join(test_df, by = "player") 
ab1 <- ab1 %>%
  mutate(ability = intercept + first_serve.y * w_serveperc)

ab2 <- losers_2015 %>% left_join(test_df, by = "player")
ab2 <- ab2 %>%
  mutate(ability = intercept + first_serve.y * l_serveperc)

## subtract player abilities to obtain the logodds that the player in ab1
## beats the player in ab2
logodds <- ab1 %>% select(ability) - 
  ab2 %>% select(ability)

## backtransform to get match predictions
pred_prob <- exp(logodds) / (1 + exp(logodds))
```


```{r}
# join pred_prob to both winners and losers 
winners_2015 <-
  bind_cols(winners_2015, pred_prob) %>%
  mutate(win = win1) %>%
  within(., rm(id, winner_name, w_serveperc, w_secondserve, win1))


losers_2015 <-
  bind_cols(losers_2015, pred_prob) %>%
  mutate(win = win2) %>%
  within(., rm(id, loser_name, l_serveperc, l_secondserve, win2)) 


# add categorical variable for probability ranges
winners_2015 <-
  winners_2015 %>%
  mutate(ranges = case_when(
    ability < 0.5 ~ "tmp",
    ability >= 0.5 & ability < 0.6 ~ "fifties",
    ability >= 0.6 & ability < 0.7 ~ "sixties",
    ability >= 0.7 & ability < 0.8 ~ "seventies",
    ability >= 0.8 & ability < 0.9 ~ "eighties",
    ability >= 0.9 ~ "nineties"
  ))

losers_2015 <-
  losers_2015 %>%
  mutate(ranges = case_when(
    1 - ability < 0.5 ~ "tmp",
    1 - ability >= 0.5 & 1 - ability < 0.6 ~ "fifties",
    1 - ability >= 0.6 & 1 - ability < 0.7 ~ "sixties",
    1 - ability >= 0.7 & 1 - ability < 0.8 ~ "seventies",
    1 - ability >= 0.8 & 1 - ability < 0.9 ~ "eighties",
    1 - ability >= 0.9 ~ "nineties"
  ))

winners_losers_2015 <-
  bind_rows(winners_2015, losers_2015) %>%
  filter(ranges == "fifties" | ranges == "sixties" | ranges == "seventies" | ranges == "eighties" | ranges == "nineties")
```


```{r}
# check percents
pred_stats <-
  winners_losers_2015 %>%
  group_by(ranges) %>%
  summarise(sum = sum(win), count = n(),
    prop = mean(win))
```

