---
title: "part1"
author: "Josh Marvald"
date: "5/23/2020"
output: html_document
---

<!-- I still can't run this....something I would try to do is to make each Markdown file it's own contained entity that can run entirely on its own.  If there's a lot of data prep code that you need to use but don't want  in the file, then you can put that code in an R file and use source("name_of_r _file") to not take up as much space. -->

<!-- Making sure each markdown file can run on its own will help you later too (it can get cumbersome to try to remember where certain data sets came from just from memory, especially the more and more stuff you do).  -->

```{r}
# gs_matches_long has duplicate matches
# only want the matches where the winner_name or loser_name for big 3 matches the 
# win indicator variable
big3<- 
  gs_matches_long %>%
  filter((winner_name == "Roger Federer" & win == 1) | (loser_name == "Roger Federer" & win == 0) | (winner_name == "Rafael Nadal" & win == 1) | (loser_name == "Rafael Nadal" & win == 0) | (winner_name == "Novak Djokovic" & win == 1) | (loser_name == "Novak Djokovic" & win == 0)) %>%
  mutate(big3_name = case_when(
    winner_name == "Roger Federer" | loser_name == "Roger Federer" ~ "Roger Federer",
    winner_name == "Rafael Nadal" | loser_name == "Rafael Nadal" ~ "Rafael Nadal",
    winner_name == "Novak Djokovic" | loser_name == "Novak Djokovic" ~ "Novak Djokovic"
  ))

ggplot(big3, aes(win, serve_percentage, color = big3_name)) +
  stat_smooth(method = "glm", method.args = c("binomial"))
```

when pivoting to long format, could try to create a variable called player name so that....

```{r}
test_df <- data.frame(matchid = c(1, 2), winningplayer = c("Nadal", "Djokovic"),
  losingplayer = c("Thiem", "Nadal"), w_serveperc = c(90, 80), l_serveperc = c(50, 60))
test_df
```

becomes....

```{r}
library(tidyverse)
long_df <- test_df %>% pivot_longer(c(winningplayer, losingplayer), 
  names_to = "winorlose", values_to = "player")
```

You could end up just stacking two data frames: one for the winning player and one for the losing player. This takes a little bit of work but it's the easiest way I could think of to figure out how to get the desired output.

```{r}
loser_stats <- long_df %>% select(-starts_with("w_")) %>% 
  filter(winorlose == "losingplayer")
names(loser_stats) <- c("matchid", "serveperc", "winorlose", "player")
winner_stats <- long_df %>% select(-starts_with("l_")) %>%
  filter(winorlose == "winningplayer")
names(winner_stats) <- c("matchid", "serveperc", "winorlose", "player")

df <- bind_rows(loser_stats, winner_stats)

## then filter by big3 (or whatever) and plot. There will be one observation
## per match if the member of the big 3 played someone else and two
## observations if members of the big 3 played each other but the plot should
## work out, colouring by player.
```


```{r}
atp_matches2017 <- read_csv("data/atp_matches_2017.csv")
```


```{r}
atp_matches2017 <- 
  atp_matches2017 %>%
  mutate(`w_serveperc` = w_1stIn/w_svpt) %>%
  mutate(`l_serveperc` = l_1stIn/l_svpt)
```


```{r}
gs_matches2017 <-
  atp_matches2017 %>%
  filter(tourney_name == "Australian Open"| tourney_name == "Wimbledon"| tourney_name == "Roland Garros"| tourney_name == "US Open")  
```


```{r}
# player column
gs_matches_long <-
  gs_matches2017 %>%
  pivot_longer(c(winner_name, loser_name), names_to = "win_loss", values_to = "player")

# matches lost
losers <- gs_matches_long %>%
  select(-starts_with("w_")) %>%
  filter(win_loss == "loser_name")

# matches won
winners <- gs_matches_long %>%
  select(-starts_with("l_")) %>%
  filter(win_loss == "winner_name")

new_gs_matches <- bind_rows(losers, winners)

# make just one variable for wether the player won
#new_gs_matches <-
#  new_gs_matches %>%
#  mutate(win = case_when(
#    win_loss == "loser_name" ~ 0,
#    win_loss == "winner_name" ~ 1
#  )) 

# big 3 glm
new_gs_matches %>%
  filter(player == "Roger Federer" | player == "Rafael Nadal" | player == "Novak Djokovic") %>%
  ggplot(., aes(x = serveperc, y = win, color = player)) +
  stat_smooth(method = "glm", method.args = c("binomial"), se = F) +
  theme_bw()

# all players glm
ggplot(new_gs_matches, aes(x = serveperc, y = win)) +
  stat_smooth(method = "glm", method.args = c("binomial"))
  
```
*this does not make sense to me for Nadal and Djokovic*
