---
title: "rf_markdown"
author: "Josh Marvald"
date: "11/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(randomForest)
source("random_forest_files/merging_variables.R")
```


```{r}
rf_df <-
  rf_df %>%
  filter(is.na(set_advantage) == F & is.na(game_advantage) == F & is.na(P1Score) == F & is.na(P2Score) == F
        & is.na(rank_dif) == F & is.na(result) == F)

rf_df$P1Score <- as.factor(rf_df$P1Score)
rf_df$P2Score <- as.factor(rf_df$P2Score)

set.seed(7)


data_size <- floor(nrow(rf_df)/2)
# Generate a random sample of "data_set_size" indexes
indexes <- sample(1:nrow(rf_df), size = data_size)
# Assign the data to the correct sets
train <- rf_df[indexes,] 
test <- rf_df[-indexes,] 
```


```{r}
rf1 <- randomForest(result ~ set_advantage + game_advantage + P1Score + P2Score + rank_dif, data = train, ntree = 100, mtry = 3, importance = T)


```


```{r}
preds <- predict(rf1, test)
test <- 
  test %>%
  ungroup %>%
  mutate(predictions = preds) 
```


```{r}
# add categorical variable for probability ranges
test <-
  test %>%
  mutate(ranges = case_when(
    predictions < .1 ~ "ones",
    predictions >= 0.1 & predictions < 0.2 ~ "tens",
    predictions >= 0.2 & predictions < 0.3 ~ "twenties",
    predictions >= 0.3 & predictions < 0.4 ~ "thirties", 
    predictions >= 0.4 & predictions < 0.5 ~ "fourties",
    predictions >= 0.5 & predictions < 0.6 ~ "fifties",
    predictions >= 0.6 & predictions < 0.7 ~ "sixties",
    predictions >= 0.7 & predictions < 0.8 ~ "seventies",
    predictions >= 0.8 & predictions < 0.9 ~ "eighties",
    predictions >= 0.9 ~ "nineties"
  )) %>%
  mutate(ranges2 = case_when(
    predictions >= 0.5 ~ "win",
    predictions < 0.5 ~ "loss"
  ))

test %>%
  group_by(ranges) %>%
  summarise(prop = mean(result))

test %>%
  group_by(ranges2) %>%
  summarise(prop = mean(result))
```





